# Generated by Django 4.0.2 on 2022-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
