# Generated by Django 4.0.2 on 2022-02-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupizer', '0005_alter_membership_role_alter_membership_user'),
        ('chat', '0002_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groupizer.group'),
        ),
    ]
