# Generated by Django 4.0.2 on 2022-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
