# Generated by Django 4.0.2 on 2022-02-04 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AddField(
            model_name='interest',
            name='users',
            field=models.ManyToManyField(related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
