# Generated by Django 4.0.2 on 2022-02-04 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupizer', '0002_remove_interest_user_interest_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
