# Generated by Django 4.0.2 on 2022-02-05 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupizer', '0004_alter_ad_group_alter_ad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('MEMBER', 'Member'), ('ADMIN', 'Admin')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
